<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Admin\About\" />
    <Folder Include="Admin\Services\" />
    <Folder Include="Admin\Projects\" />
    <Folder Include="Admin\Skills\" />
  </ItemGroup>

</Project>
